BrainThud.Web/Controllers/CardsController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using BrainThud.Core;
using BrainThud.Web.Data.AzureTableStorage;

namespace BrainThud.Web.Controllers
{
    public class CardsController : Controller
    {
        private readonly Lazy<ITableStorageContext> lazyTableStorageContext;
        private ITableStorageContext TableStorageContext { get { return this.lazyTableStorageContext.Value; } }

        public CardsController(ITableStorageContextFactory tableStorageContextFactory)
        {
            this.lazyTableStorageContext = new Lazy<ITableStorageContext>(() =>
                tableStorageContextFactory.CreateTableStorageContext(AzureTableNames.CARD));
        }

        //
        // GET: /Library/

        public ActionResult Index()
        {
            var cardDecks = this.TableStorageContext.CardDecks.GetAll().ToList();

#if !DEBUG
            cardDecks = cardDecks.Where(x => x.PartitionKey != ConfigurationSettings.TEST_PARTITION_KEY && 
                x.PartitionKey != ConfigurationSettings.DEV_PARTITION_KEY && 
                x.PartitionKey != ConfigurationSettings.DEV_PARTITION_KEY_2).ToList();
#endif

            return View(cardDecks.OrderBy(x => x.DeckName));
        }

        //
        // GET: /cards/5/342

        public ActionResult Deck(int userId, string deckNameSlug)
        {
            // Temp until google re-indexes pages
            if(userId == 76)  return RedirectToRoutePermanent(RouteNames.DECK, new {userId = 5218, deckNameSlug = deckNameSlug});
            if (userId == 1040) return RedirectToRoutePermanent(RouteNames.DECK, new { userId = 5217, deckNameSlug = deckNameSlug });

            // Shouldn't use slug because it could be duplicated
            deckNameSlug = deckNameSlug.ToLower();
            var userConfiguration = this.TableStorageContext.UserConfigurations.GetByUserId(userId);
            var partitionKey = userConfiguration.PartitionKey;
            var cards = this.TableStorageContext.Cards.Get(partitionKey)
                .Where(x => x.DeckNameSlug == deckNameSlug)
                .ToList();

            return View("card-deck", cards);
        }

        public ActionResult Card(int userId, int cardId)
        {
            // Temp until google re-indexes pages
            if(userId == 76 || userId == 1040)
            {
                var cardSlug = HttpContext.Request.Url.Segments.Last();
                if (userId == 76) return RedirectToRoutePermanent(RouteNames.CARD, new { userId = 5218, cardId = cardId, cardSlug = cardSlug });
                if (userId == 1040) return RedirectToRoutePermanent(RouteNames.CARD, new { userId = 5217, cardId = cardId, cardSlug = cardSlug });
            }

            var userConfiguration = this.TableStorageContext.UserConfigurations.GetByUserId(userId);
            var partitionKey = userConfiguration.PartitionKey;
            var card = this.TableStorageContext.Cards.GetByPartitionKey(partitionKey, cardId);
            return View("card", card);
        }
    }
}

BrainThud.Web/Controllers/HomeController.cs
using System.Web.Mvc;

namespace BrainThud.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

       [Authorize]
       public ActionResult Home()
        {
            return View("home");
        }
    }
}

BrainThud.Web/Views/Home/Index.cshtml
@{
    const string TAG_LINE = "Flashcards done right";
    ViewBag.Title = "BrainThud - " + TAG_LINE;
    Layout = "~/Views/Shared/_public-layout.cshtml";
    ViewBag.HideNavBar = true;
}

<div class="row-fluid">
    <div class="span12">
        <img class="image-center-align home-logo" src="~/Images/logo-and-title-top-280.png" />
    </div>
</div>
<div class="row-fluid skip-line">
    <div class="span12">
        <h2 class="center-align">@TAG_LINE</h2>
        <div class="center-align strong">(Beta)</div>
    </div>
</div>
<div class="row-fluid skip-line">
    <div class="span3 offset1">
        @Html.ActionLink("Browse Flashcards", "Index", "Cards", null, new { @class = "btn btn-warning primary-button" })
    </div>
    <div class="span4">
        @Html.ActionLink("Sign Up", "Login", "Account", null, new { @class = "btn btn-primary primary-button" })
    </div>
    <div class="span3">
        @Html.ActionLink("Log In", "Login", "Account", null, new { @class = "btn btn-success primary-button" })
    </div>
</div>

BrainThud.Web/Views/Home/home.cshtml
@using BrainThud.Core
@{
    ViewBag.Title = "BrainThud";
}
    
@section menu {
    <li>@Html.ActionLink("Browse", "Index", "Cards")</li>
    <li><a href="" data-bind="click: goToLibrary" data-toggle="collapse" data-target=".nav-collapse">Library</a></li>
    <li><a href="" data-bind="click: goToCreateCard" data-toggle="collapse" data-target=".nav-collapse">Create Card</a></li>
    <li><a href="" data-bind="click: goToQuiz" data-toggle="collapse" data-target=".nav-collapse">Quiz</a></li>
    <li><a href="" data-bind="click: goToUserConfiguration" data-toggle="collapse" data-target=".nav-collapse">Settings</a></li>
}

@RenderPage("~/Views/card.cshtml")
@RenderPage("~/Views/create-card.cshtml")
@RenderPage("~/Views/library.cshtml")
@RenderPage("~/Views/quiz.cshtml")
@RenderPage("~/Views/quiz-card.cshtml")
@RenderPage("~/Views/user-configuration.cshtml")
@RenderPage("~/Views/delete-card-dialog.cshtml")
@RenderPage("~/Views/card-info-dialog.cshtml")
@RenderPage("~/Views/session-expired-dialog.cshtml")

@section outsideMain {
    <div id="loading">
        <img src="~/Images/loading.gif" />
    </div>
}

@section Scripts {
    @Scripts.Render(
        BundlePaths.EXTERNAL_LIBS,
        ScriptPaths.REQUIRE_JS,
        BundlePaths.APP_LIBS,
        ScriptPaths.MAIN_JS)

   <script type="text/javascript">
        var uvOptions = {};
        (function() {
            var uv = document.createElement('script');
            uv.type = 'text/javascript';
            uv.async = true;
            uv.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'widget.uservoice.com/UCF5knvUK7R0PeH2KK7w.js';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(uv, s);
        })();
    </script>
}